"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.examplesButton = exports.exampleItemRenderer = exports.exampleGrid = exports.dialogMessage = exports.dialogTitle = exports.versionLabel = exports.requestIcon = exports.dialog = void 0;
// import * as view from "./Elements.js";
exports.dialog = document.querySelector("#dialog");
exports.requestIcon = document.querySelector("#requestIcon");
exports.versionLabel = document.querySelector("#versionLabel");
exports.dialogTitle = document.querySelector("#dialogTitle");
exports.dialogMessage = document.querySelector("#dialogMessage");
exports.exampleGrid = document.querySelector("#exampleGrid");
exports.exampleItemRenderer = document.querySelector("#exampleItemRenderer");
exports.examplesButton = document.querySelector("#examplesButton");
